### ISSUE TITLE
SDE parity checklist

### ISSUE THREAD

**Issue by CarbonAlabel** [esi/esi-issues#1103]
This checklist consists of all the files from the SDE, a short description of their contents, and the current status of an ESI replacement for them, with the purpose of showing how close ESI is to achieving SDE parity.

Checked boxes indicate that a part of the SDE has an ESI equivalent or is in some way obsolete, while unchecked ones mean that more work is required to reach parity. If you disagree on my judgement on some of them, or think I've missed something, feel free to comment on this issue.

- [ ] `blueprints.yaml`
    Blueprint details.
    Not available: https://github.com/esi/esi-issues/issues/501
- [x] `categoryIDs.yaml`
    Inventory category definitions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_categories_category_id
- [ ] `certificates.yaml`
    Mastery certificate definitions.
    Not available.
- [x] `graphicIDs.yaml`
    Some kind of graphics stuff.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_graphics_graphic_id
- [x] `groupIDs.yaml`
    Inventory group definitions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_groups_group_id
- [x] `iconIDs.yaml`
    Icon ID to file mapping.
    Icons should be available through the image server.
- [ ] `skinLicenses.yaml`, `skinMaterials.yaml`, `skins.yaml`
    SKIN details.
    Not available.
- [x] `tournamentRuleSets.yaml`
    Tournament rules, including banned ships, ship point values, and team sizes. 
    Should be given the same treatment as the CREST tournament endpoints.
- [x] `typeIDs.yaml`
    Inventory type definitions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_types_type_id
- [ ] `universe`
    Multiple levels of folders (universe, region, constellation, solar system) containing .staticdata files describing their properties. The files for solar systems also contain details of all celestials inside that system.
    Available under various endpoints, but with some attributes missing:
    - [ ] Regions: faction, wormhole class, coordinates
    - [ ] Constellations: radius, min/max coordinates
    - [ ] Systems: radius, min/max coordinates, disallowed anchoring, various positional properties (border, corridor, fringe, hub...)
    - [x] Stars
    - [x] Stargates
    - [ ] Planets and moons: radius, celestial index, statistics
    - [ ] Asteroid belts: statistics
- [ ] `landmarks`
    Important locations that are shown in space on the old map. No way to resolve the name and description IDs to strings.
    Not available.
- [ ] `agtAgentTypes.yaml`, `agtAgents.yaml`, `agtResearchAgents.yaml`
    NPC agent details.
    Not available: https://github.com/esi/esi-issues/issues/863 https://github.com/esi/esi-issues/issues/1064
- [x] `chrAncestries.yaml`
    Character ancestries.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_ancestries
- [x] `chrAttributes.yaml`
    Skill attribute descriptions.
    Not available, unused.
- [ ] `chrBloodlines.yaml`
    Character bloodlines.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_bloodlines
    Missing male/female descriptions and short descriptions.
- [x] `chrFactions.yaml`
    NPC factions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_factions
- [ ] `chrRaces.yaml`
    Character races.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_races
    Missing short descriptions, only returning the four playable races.
- [x] `crpActivities.yaml`
    Activities which NPC corporations engage in, don't appear to be referenced anywhere else.
    Not available, unused.
- [x] `crpNPCCorporationDivisions.yaml`
    Percentages of the corporations' agents belonging to each division.
    Not available, redundant.
- [x] `crpNPCCorporationResearchFields.yaml`
    Fields in which the corporations have research agents.
    Not available, redundant.
- [x] `crpNPCCorporationTrades.yaml`
    Types which NPC corporations sell on the market.
    Not available, but can be seen on the market itself.
- [ ] `crpNPCCorporations.yaml`
    Available: https://esi.evetech.net/ui/?version=_dev#/Corporation/get_corporations_npccorps https://esi.evetech.net/ui/?version=_dev#/Corporation/get_corporations_corporation_id
    Missing various lore trivia, unable to get NPC corp faction ID: https://github.com/esi/esi-issues/issues/765 https://github.com/esi/esi-issues/issues/917
- [ ] `crpNPCDivisions.yaml`
    NPC corp division names.
    Should be enumified.
- [ ] `dgmAttributeCategories.yaml`
    Dogma attribute category definitions.
    Not available.
- [x] `dgmAttributeTypes.yaml`
    Dogma attribute definitions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Dogma/get_dogma_attributes_attribute_id
- [x] `dgmEffects.yaml`
    Dogma effect definitions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Dogma/get_dogma_effects_effect_id
- [ ] `dgmExpressions.yaml`
    Another piece of the dogma puzzle.
    Not available: https://github.com/esi/esi-issues/issues/1021
- [x] `dgmTypeAttributes.yaml`
    Dogma attribute values.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_types_type_id
- [x] `dgmTypeEffects.yaml`
    Dogma effect assignments.
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_types_type_id
- [ ] `eveUnits.yaml`
    Units used by dogma attributes.
    Not available: https://github.com/esi/esi-issues/issues/404
- [ ] `invContrabandTypes.yaml`
    Types considered illegal in space of certain factions.
    Not available.
- [ ] `invControlTowerResourcePurposes.yaml`, `invControlTowerResources.yaml`
    Describes the fuel types, including charters, used by control towers.
    Not available.
- [x] `invFlags.yaml`
    Names of inventory location flags.
    Available: https://github.com/esi/eve-glue/blob/master/eve_glue/location_flag.py
- [x] `invItems.yaml`
    Inventory contents of CCP created EVE entities.
    Not available, unused.
- [x] `invMarketGroups.yaml`
    Market group definitions.
    Available: https://esi.evetech.net/ui/?version=_dev#/Market/get_markets_groups_market_group_id
- [ ] `invMetaGroups.yaml`
    Meta group definitions.
    Not available.
- [ ] `invMetaTypes.yaml`
    Meta group values.
    Not available.
- [x] `invNames.yaml`
    Names of EVE entities.
    Available on individual endpoints.
- [x] `invPositions.yaml`
    Coordinates of all the items from invItems.yaml.
    Not available, unused.
- [ ] `invTypeMaterials.yaml`
    Reprocessing output.
    Not available: https://github.com/esi/esi-issues/issues/664
- [x] `invTypeReactions.yaml`
    Old style reaction details.
    Not available, unused.
- [x] `invUniqueNames.yaml`
    Subset of invNames.yaml with type categories added.
- [x] `mapUniverse.yaml`
    Not available, unused.
- [ ] `planetSchematics.yaml`, `planetSchematicsPinMap.yaml`, `planetSchematicsTypeMap.yaml`
    PI schematic details.
    Not available: https://github.com/esi/esi-issues/issues/646 https://github.com/esi/esi-issues/issues/1066
- [ ] `ramActivities.yaml`
    Industrial activity type definitions.
    Should be enumified: https://github.com/esi/esi-issues/issues/894 https://github.com/esi/esi-issues/issues/997
- [x] `ramAssemblyLineStations.yaml`, `ramAssemblyLineTypeDetailPerCategory.yaml`, `ramAssemblyLineTypeDetailPerGroup.yaml`, `ramAssemblyLineTypes.yaml`, `ramInstallationTypeContents.yaml`
    Old slot-based industry definitions.
    Unused.
- [ ] `staOperationServices.yaml`, `staOperations.yaml`
    Used to assign station names, descriptions, and available services.
    Available, missing station descriptions: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_stations_station_id
- [ ] `staServices.yaml`
    Station service definitions.
    Enumified in https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_stations_station_id
    Not available in https://github.com/esi/eve-glue
- [ ] `staStationTypes.yaml`
    Undock point position and orientation for stations.
    Not available.
- [x] `staStations.yaml`
    Available: https://esi.evetech.net/ui/?version=_dev#/Universe/get_universe_stations_station_id
- [x] `trnTranslationColumns.yaml`, `trnTranslationLanguages.yaml`, `trnTranslations.yaml`
    Individual endpoints should have translation built in.
- [x] `warCombatZoneSystems.yaml`, `warCombatZones.yaml`
    Contains information about original owners of FW systems.
    Available: https://esi.evetech.net/ui/?version=_dev#/Faction%20Warfare/get_fw_systems

**Comment by tsuthers-ccpgames** [comment]
Thoughts on this list:

1. Races and bloodlines are both pretty small, could they usefully be combined into one endpoint?
2. is contraband even still a thing?
3. At least some of the planet schematic stuff is covered in the PI endpoints, right? Do we just need some kind of index list for the PI schematics so you can know the full set?

**Comment by tsuthers-ccpgames** [comment]
Also, it's a monster but localization isn't on this list and I know it's in the SDE. The performance implications of letting people traverse it via API might be pretty bad though, loading the entire localization tree can take a few minutes on a desktop with an SSD.

**Comment by CarbonAlabel** [comment]
1. Could also squeeze ancestries in there, but why? They all already have their own endpoints.
2. Would making it not a thing at all be an option?
3. It's also that the current schematic endpoint doesn't tell you anything about what its inputs/outputs are.
4. Didn't forget about it, it's marked as completed on the list since most endpoints have built in localization.

**Comment by tsuthers-ccpgames** [comment]
Ah, I thought they were unticked because they were totally missing, but I see they're just missing some stuff.

**Comment by rayanth** [comment]
https://esi.evetech.net/ui/?version=_dev#/Market/get_markets_groups_market_group_id  does not return the iconid that is in the yaml. We still need the SDE to link a market group to its icon, since the icon id's are not the same numbering.

**Comment by CarbonAlabel** [comment]
Since both the SDE and the IEC (which is where you'd most likely get the icon itself from) are on the track to be deprecated, a proper solution would be ensuring the image server can directly return the icons for market groups.

**Comment by GoldenGnu** [comment]
`invFalgs.yaml` is marked as done, but, there is no way to translate the enum value to the text used in-game. Glue only translate the enum to the sde flag_id. This is true for almost all the enum values in ESI

**Comment by rayanth** [comment]
> Since both the SDE and the IEC (which is where you'd most likely get the icon itself from) are on the track to be deprecated, a proper solution would be ensuring the image server can directly return the icons for market groups.

Agreed, but the further I dig, the further it makes less sense - 
/universe/types/{type_id}/ has the icon_id, but /universe/groups/{group_id}/ and /universe/categories/{category_id}/ do not.

**Comment by GoldenGnu** [comment]
`typeIDs.yaml` is marked as done, but, there is no way to get `basePrice` in ESI

**Comment by rayanth** [comment]
`typeIDs.yaml` is marked as done, but, there is no way to get `race` in ESI on ships
