### ISSUE TITLE
Accept-Language headers not interpreted correctly

### ISSUE THREAD

**Issue by lukasni** [esi/esi-issues#1196]
# Bug

ESI seems not to fully respect the Accept-Language headers sent by some browsers. I've been able to observe the following issues:

- Case sensitive, `en-US`, which is the correct casing of the region variant, will _not_ return an english result if other supported languages are also in the header, such as with `Accept-Language: en-US,de`
- `en`, without the region variant, is not accepted
- q-factor weighting is not respected, ESI will simply return the first recognized language.

Confirmed on multiple `/universe/` routes, I assume all routes are affected.

This is an issue because it can result in things like this: 
![image](https://user-images.githubusercontent.com/5263957/79928461-df9d2500-83f7-11ea-86de-785d1961b635.png)

## Examples

Breaking the recommended formatting a bit to show a few example request/response pairs that showcase the issues listed above. Responses are trimmed for brevity

### Request / Response pair 1, `en-US` and `en` ignored

`curl -iH GET "https://esi.evetech.net/latest/universe/types/34/?datasource=tranquility" -H "accept: application/json" -H "Accept-Language: en-US,en,de" `

```
HTTP/2 200
content-language: de
x-esi-request-id: 8991f97b-2b38-4faa-b2bd-22bdb456a78a

{"capacity":0.0,"description":"Die grundlegende Basiskomponente aller Strukturen im All. [...]","group_id":18,"icon_id":22,"market_group_id":1857,"mass":0.0,"name":"Tritanium","packaged_volume":0.01,"portion_size":1,"published":true,"radius":1.0,"type_id":34,"volume":0.01}
```

### Request / Response pair 2, q-factor ignored.

`curl -iH GET "https://esi.evetech.net/latest/universe/types/34/?datasource=tranquility" -H "accept: application/json" -H "Accept-Language: en-us;q=0.5,de;q=0.7"`

```
HTTP/2 200
content-language: en-us
x-esi-request-id: e0452241-8dd5-4fd0-b5b4-a44165ed857f

{"capacity":0.0,"description":"The main building block in space structures. [...]","group_id":18,"icon_id":22,"market_group_id":1857,"mass":0.0,"name":"Tritanium","packaged_volume":0.01,"portion_size":1,"published":true,"radius":1.0,"type_id":34,"volume":0.01}
```

## Expected

Results in the right language

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by mateuszkrasucki** [comment]
Fixed, all mentioned cases work correctly for some time now.
