### ISSUE TITLE
Devblogs give wrong URL on official CCP website

### ISSUE THREAD

**Issue by jeronica** [esi/esi-issues#964]
# Inconsistency

Devblog on official website points to wrong domain. The "quick reference" tells people to go to https://esi.tech.ccp.is/ when it should say to use https://esi.evetech.net/

## Routes

https://developers.eveonline.com/blog/article/esi-quick-reference-for-new-developers
https://developers.eveonline.com/blog/article/esi-quick-reference-for-new-developers-1

## Resolution
If the evetech.net address really is the correct domain to be using, replace the ccp.is address with evetech.net address.

# Checklist

Check all boxes that apply to this issue:

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [x] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by tsuthers-ccpgames** [comment]
This has been fixed. There was a publishing irregularity with the first one which caused duplicate articles to be created. The same irregularity prevented us from being able to update the first of the two links you provided. 

We elected to delete both of those articles and create a new one under a new URL. It sucks a little because links to the old ones will break but it's better than having one blog with old info and one with new info.

The new article with the updated links is here: https://developers.eveonline.com/blog/article/updated-esi-quick-reference-for-new-developers
