### ISSUE TITLE
[Bug][meta]? https://status.esi.evetech.net/ doesn't detect 520s and timeouts

### ISSUE THREAD

**Issue by DaneelTrevize** [esi/esi-issues#973]
# Bug

30 failures today, 21 recently within a 15 minute window (the last 3 being >10second timeouts rather than 520 'node dead's), yet no incident or bad status is noted on https://status.esi.evetech.net/ or https://esi.evetech.net/ui/

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET https://esi.tech.ccp.is/v1/fleets/1017211444689/`
`GET https://esi.tech.ccp.is/v1/fleets/1017211444689/members/`
`GET https://esi.tech.ccp.is/v1/fleets/1017211444689/wings/`

## Response

	Line 3: ERROR - 2018-06-18 00:24:39 --> LibCachedESI: $failures: Array
	Line 44: ERROR - 2018-06-18 00:24:39 --> LibCachedESI: $failures: Array
	Line 97: ERROR - 2018-06-18 00:24:40 --> LibCachedESI: $failures: Array
	Line 151: ERROR - 2018-06-18 00:27:49 --> LibCachedESI: $failures: Array
	Line 192: ERROR - 2018-06-18 00:27:50 --> LibCachedESI: $failures: Array
	Line 245: ERROR - 2018-06-18 00:27:51 --> LibCachedESI: $failures: Array
	Line 299: ERROR - 2018-06-18 00:29:52 --> LibCachedESI: $failures: Array
	Line 340: ERROR - 2018-06-18 00:29:53 --> LibCachedESI: $failures: Array
	Line 393: ERROR - 2018-06-18 00:29:53 --> LibCachedESI: $failures: Array
	Line 449: ERROR - 2018-06-18 02:53:26 --> LibCachedESI: $failures: Array
	Line 490: ERROR - 2018-06-18 02:53:26 --> LibCachedESI: $failures: Array
	Line 543: ERROR - 2018-06-18 02:53:26 --> LibCachedESI: $failures: Array
	Line 616: ERROR - 2018-06-18 18:48:23 --> LibCachedESI: $failures: Array
	Line 657: ERROR - 2018-06-18 18:48:23 --> LibCachedESI: $failures: Array
	Line 710: ERROR - 2018-06-18 18:48:23 --> LibCachedESI: $failures: Array
	Line 764: ERROR - 2018-06-18 18:48:55 --> LibCachedESI: $failures: Array
	Line 805: ERROR - 2018-06-18 18:48:55 --> LibCachedESI: $failures: Array
	Line 858: ERROR - 2018-06-18 18:48:55 --> LibCachedESI: $failures: Array
	Line 912: ERROR - 2018-06-18 18:49:33 --> LibCachedESI: $failures: Array
	Line 953: ERROR - 2018-06-18 18:49:33 --> LibCachedESI: $failures: Array
	Line 1006: ERROR - 2018-06-18 18:49:34 --> LibCachedESI: $failures: Array
	Line 1060: ERROR - 2018-06-18 18:50:11 --> LibCachedESI: $failures: Array
	Line 1101: ERROR - 2018-06-18 18:50:11 --> LibCachedESI: $failures: Array
	Line 1154: ERROR - 2018-06-18 18:50:12 --> LibCachedESI: $failures: Array
	Line 1208: ERROR - 2018-06-18 18:51:11 --> LibCachedESI: $failures: Array
	Line 1249: ERROR - 2018-06-18 18:51:11 --> LibCachedESI: $failures: Array
	Line 1302: ERROR - 2018-06-18 18:51:11 --> LibCachedESI: $failures: Array
	Line 1356: ERROR - 2018-06-18 18:52:44 --> LibCachedESI: $failures: Array
	Line 1397: ERROR - 2018-06-18 18:52:44 --> LibCachedESI: $failures: Array
	Line 1450: ERROR - 2018-06-18 18:52:45 --> LibCachedESI: $failures: Array
	Line 1506: ERROR - 2018-06-18 19:02:56 --> LibCachedESI: $failures: Array
	Line 1521: ERROR - 2018-06-18 19:03:06 --> LibCachedESI: $failures: Array
	Line 1546: ERROR - 2018-06-18 19:03:16 --> LibCachedESI: $failures: Array

### Status Code

`520`

### Headers

[0] => HTTP/1.1 520 status code 520
[1] => Date: Mon, 18 Jun 2018 18:53:28 GMT
[2] => Content-Type: application/json; charset=UTF-8
[3] => Content-Length: 129
[4] => Connection: keep-alive
[5] => Access-Control-Allow-Credentials: true
[6] => Access-Control-Allow-Headers: Content-Type,Authorization,If-None-Match,X-User-Agent
[7] => Access-Control-Allow-Methods: GET,POST,HEAD,OPTIONS
[8] => Access-Control-Allow-Origin: *
[9] => Access-Control-Expose-Headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
[10] => Access-Control-Max-Age: 600
[11] => Allow: GET,HEAD,OPTIONS,POST
[12] => Content-Language: en-us
[13] => Strict-Transport-Security: max-age=31536000
[14] => Vary: Accept-Language
[15] => X-Esi-Error-Limit-Remain: 98
[16] => X-Esi-Error-Limit-Reset: 32
[17] => X-Esi-Request-Id: 7ee717a2-2122-4f6e-91ce-a6232624def1

### Body

{"error":"{'error_label': 'UnMachoDestination', 'error_dict': {'what': 'The specified proxy or server node (1444689) is dead'}}"}

## Expected

`200`

_JSON of fleet/member/wing details_.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by jowrjowr** [comment]
...and what should ESI be doing here?

You have an error. Deal with it.

**Comment by rawrasaur** [comment]
ESI was up, EVE was down, deal with it.

**Comment by DaneelTrevize** [comment]
`...and what should ESI be doing here?

You have an error. Deal with it.`

One assumes the bloody https://status.esi.evetech.net/ page might accurately reflect that there's issue with the endpoints.

**Comment by jowrjowr** [comment]
it does. but it isn't perfect, as you can see. also there are thresholds for determining whether an endpoints status. 

ESI errors sometimes. deal with it. please don't make bullshit issues about things that have literally no solution. 

imma lock dis
